#LENGTH
LENGTH_LINK = 6
MAX_CUSTOM_LINK_LENGTH = 15
MAX_MODEL_ORIGINAL_LENGTH = 256
MAX_MODEL_SORT_LENGTH = 64
MAX_FORM_LENGTH = 128
MIN_FORM_LENGTH = 1

FORBIDDEN_EXPRESSIONS = [
      '.,/!?', 'Hodor-Hodor', 'h@k$r', '$', 'п', 'l l'
]

#STATUS_CODE
STATUS_CODE_OK = 200
STATUS_CODE_CREATED = 201
STATUS_CODE_BAD_REQUEST = 400
STATUS_CODE_NOT_FOUND = 404
